revive:
  build: ../docker
  container_name: revive
  ports:
    - "80:80"
    - "443:443"
  restart: always
  volumes:
    - ./../app:/var/www/html
    - ./../log:/var/log/nginx
    - ./../server/ssl:/etc/ssl
    - ./../server/nginx.conf:/etc/nginx/nginx.conf
    - ./../server/ssl-ads-beritagar.id.conf:/etc/nginx/conf.d/ssl-ads-beritagar.id.conf
    - ./../server/ads-beritagar.id.conf:/etc/nginx/conf.d/ads-beritagar.id.conf
    - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
